import os
import sys
import shutil
from setuptools import setup
from Cython.Build import cythonize

# List of core Python files to compile into binary modules
FILES_TO_COMPILE = [
    "database.py",
    "binance_client.py",
    "crypto_verifier.py",
    "keyboards.py",
    "localization.py",
    "api.py",
    "cryptobot_client.py"
]

def compile_files():
    print("[INFO] Starting Cython compilation for Linux...")
    
    # We compile the files inplace
    try:
        setup(
            ext_modules=cythonize(
                FILES_TO_COMPILE, 
                compiler_directives={'language_level': "3"},
                exclude=[]
            ),
            script_args=["build_ext", "--inplace"]
        )
        print("[SUCCESS] Compilation completed successfully!")
    except Exception as e:
        print(f"[ERROR] Compilation failed: {e}")
        sys.exit(1)

    # Clean up build folders and original .py files
    print("[CLEANUP] Removing build directories and source .py files...")
    
    # Remove build directories generated by setuptools
    for folder in ["build", "temp"]:
        if os.path.exists(folder):
            shutil.rmtree(folder)
            
    # Remove generated C source files and original Python source files
    for filename in FILES_TO_COMPILE:
        c_file = filename.replace(".py", ".c")
        if os.path.exists(c_file):
            os.remove(c_file)
            
        # Delete original .py file to keep only the compiled .so library
        if os.path.exists(filename):
            os.remove(filename)
            print(f"[CLEANUP] Deleted source file: {filename}")

if __name__ == "__main__":
    compile_files()
